{% set name = "robocorp-vault" %}
{% set version = "1.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robocorp_vault-{{ version }}.tar.gz
  sha256: 3635708bddf2209b415c4406cef9b7584402559f7b96f52ca4a1be0788690785

build:
  noarch: python
  script:
    - echo f | xcopy /f /y /S %RECIPE_DIR%\README.md %SRC_DIR%\README.md  # [win]
    - cp -R {{ RECIPE_DIR }}/README.md {{ SRC_DIR }}/README.md  # [unix]
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - cryptography >=42.0.4,<44.0.0
    - requests >=2.31.0,<3.0.0
    - pyyaml >=6.0.0,<7.0.0
    - tenacity >=8.0.1,<9.0.0

test:
  imports:
    - robocorp.vault
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/robocorp/robo/
  summary: Robocorp Control Room Vault API integration library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
