{% set name = "robocorp-vault" %}
{% set version = "1.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/robocorp_vault-{{ version }}.tar.gz
  sha256: 17fae413da9164536452c13d770afc7cc5d0877695c14ded66777583ac0c8e5d

build:
  noarch: python
  script:
    - echo f | xcopy /f /y /S %RECIPE_DIR%\README.md %SRC_DIR%\README.md  # [win]
    - cp -R {{ RECIPE_DIR }}/README.md {{ SRC_DIR }}/README.md  # [unix]
    - {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - cryptography >=42.0.4,<44.0.0
    - requests >=2.31.0,<3.0.0
    - pyyaml >=6.0.0,<7.0.0
    - tenacity >=8.0.1,<9.0.0

test:
  imports:
    - robocorp.vault
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/robocorp/robo/
  summary: Robocorp Control Room Vault API integration library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
